export const CHANGE_TOP_BANNERS = "CHANGE_TOP_BANNERS";
export const CHANGE_HOT_RECOMMEND = "CHANGE_HOT_RECOMMEND";
export const CHANGE_NEW_ALBUM = "CHANGE_NEW_ALBUM";

export const CHANGE_TOP_RANKING = "CHANGE_TOP_RANKING";
export const CHANGE_NEW_RANKING = " CHANGE_NEW_RANKING";
export const CHANGE_ORIGIN_RANKING = "CHANGE_ORIGIN_RANKING";

export const CHANGE_ENTER_SINGER = "CHANGE_ENTER_SINGER";
